name: Cloaker Breaker Worker

on:
  workflow_dispatch: # Permite rodar manualmente pelo bot√£o no GitHub
  schedule:
    - cron: '*/5 * * * *' # Roda a cada 5 minutos

jobs:
  breaker-process:
    runs-on: ubuntu-latest
    timeout-minutes: 5 
    
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      # PROXY_SERVER: ${{ secrets.PROXY_SERVER }} 

    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Install Dependencies
        # AQUI ESTAVA O ERRO. Mudamos de 'npm ci' para 'npm install'
        run: npm install
        
      - name: Install Playwright Browsers
        run: npx playwright install chromium
        
      - name: Run Cloaker Breaker
        run: node cloaker_worker.mjs
